import React from 'react';
import { Shield } from 'lucide-react';

export const TermsPage: React.FC = () => {
  return (
    <div style={{ maxWidth: '800px', margin: '40px auto', padding: '0 20px', textAlign: 'left', lineHeight: '1.6' }}>
      <div className="glass-panel" style={{ padding: '40px' }}>
        <h2 style={{ fontSize: '1.8rem', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px' }}>
          <Shield size={24} style={{ color: 'var(--accent)' }} /> Terms & Conditions
        </h2>
        <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', marginBottom: '24px' }}>
          Last updated: July 8, 2026
        </p>

        <section style={{ marginBottom: '24px' }}>
          <h4 style={{ fontSize: '1.1rem', marginBottom: '10px', color: '#e6edf3' }}>1. Acceptance of Terms</h4>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.92rem' }}>
            By registering, logging in, or connecting your GitHub account to MendCode, you agree to comply with and be bound by these Terms of Service. If you do not agree, please do not use the application.
          </p>
        </section>

        <section style={{ marginBottom: '24px' }}>
          <h4 style={{ fontSize: '1.1rem', marginBottom: '10px', color: '#e6edf3' }}>2. AI Agent Autonomous Execution</h4>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.92rem' }}>
            MendCode uses autonomous AI agents to analyze repository issues and modify source code files. While we validate syntax correctness, code changes are generated by third-party LLM providers. You retain ultimate responsibility for reviewing and testing all proposed changes before merging pull requests.
          </p>
        </section>

        <section style={{ marginBottom: '24px' }}>
          <h4 style={{ fontSize: '1.1rem', marginBottom: '10px', color: '#e6edf3' }}>3. GitHub Token Authorization</h4>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.92rem' }}>
            To perform repository operations (cloning, branch creations, pull requests), you grant MendCode permissions via a GitHub OAuth Access Token. We encrypt this token securely at rest and use it exclusively for executing the agent tasks you explicitly initiate.
          </p>
        </section>

        <section style={{ marginBottom: '24px' }}>
          <h4 style={{ fontSize: '1.1rem', marginBottom: '10px', color: '#e6edf3' }}>4. Disclaimer of Warranties</h4>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.92rem', fontStyle: 'italic' }}>
            THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY.
          </p>
        </section>
      </div>
    </div>
  );
};
